<a href="https://colab.research.google.com/github/DileepKumarIrri/gitdemo1/blob/main/ML2PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

data = load_iris(as_frame = True)
df = data.frame

X = df[data['feature_names']]
print(X)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [ ]:
X_mean = X.mean()
X_std = X.std()
Z = (X-X_mean)/X_std
c = Z.cov()

eigval, eigvec = np.linalg.eig(c)

print(eigval)
print(eigvec)

[2.91849782 0.91403047 0.14675688 0.02071484]
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [ ]:
explained_var = np.cumsum(eigval) / np.sum(eigval)
print(explained_var)

[0.72962445 0.95813207 0.99482129 1.        ]


In [ ]:
n_components = np.argmax(explained_var >= 0.50)+1
print(n_components)

1


In [ ]:
u = eigvec[:,:n_components]
print(u)
pca_component = pd.DataFrame(u,
                             index = data['feature_names'],
                             columns = ['PC1']
                            )
print(pca_component)

[[ 0.52106591]
 [-0.26934744]
 [ 0.5804131 ]
 [ 0.56485654]]
                        PC1
sepal length (cm)  0.521066
sepal width (cm)  -0.269347
petal length (cm)  0.580413
petal width (cm)   0.564857


In [ ]:
Z_pca = Z @ pca_component
print(Z_pca)

          PC1
0   -2.257141
1   -2.074013
2   -2.356335
3   -2.291707
4   -2.381863
..        ...
145  1.864258
146  1.559356
147  1.516091
148  1.368204
149  0.957448

[150 rows x 1 columns]


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
pca.fit(Z)
x_pca = pca.transform(Z)

df_pca1 = pd.DataFrame(x_pca,
                       columns=['PC{}'.
                       format(i+1)
                        for i in range(n_components)])
print(df_pca1)

          PC1
0   -2.257141
1   -2.074013
2   -2.356335
3   -2.291707
4   -2.381863
..        ...
145  1.864258
146  1.559356
147  1.516091
148  1.368204
149  0.957448

[150 rows x 1 columns]
